name=AdafruitADA4991
version=0.0.0
author=mumanchu <info@muman.ch>
maintainer=mumanchu <info@muman.ch>
sentence=Library for the Adafruit ADA4991 I2C module with rotary encoder and Neopixel LED
paragraph=
category=Device Control
includes=AdafruitADA4991.h
url=https://github.com/mumanchu/AdafruitADA4991
architectures=STM32

